export type Vibe = "rave" | "darty" | "kickback" | "house" | "bar" | "club";
export type Source =
  | "eventbrite"
  | "plotz"
  | "partiful"
  | "user"
  | "dice"
  | "campus"
  | "promoter"
  | "curated";
export type SourceCategory = "imported" | "community" | "campus" | "promoter" | "curated";

export interface FunctionEvent {
  id: string;
  name: string;
  vibe: Vibe;
  area: string;
  time: string;
  source: Source;
  fire: number;
  lat: number;
  lng: number;
  gradient: string; // CSS gradient for card hero
  description?: string;
  crowd?: string;
  dress?: string;
  host?: string;
}

export const VIBE_CONFIG: Record<Vibe, { label: string; color: string }> = {
  rave: { label: "RAVE", color: "#dc2743" },
  darty: { label: "DARTY", color: "#f0854a" },
  kickback: { label: "KICKBACK", color: "#34d399" },
  house: { label: "HOUSE PARTY", color: "#f472b6" },
  bar: { label: "BAR NIGHT", color: "#60a5fa" },
  club: { label: "CLUB EVENT", color: "#a855f7" },
};

export const SOURCE_CATEGORY_CONFIG: Record<
  SourceCategory,
  { label: string; description: string; color: string; bg: string }
> = {
  imported: {
    label: "Imported",
    description: "Nightlife and ticketing listings",
    color: "#fff",
    bg: "#6d5dfc",
  },
  community: {
    label: "Community",
    description: "User-submitted functions",
    color: "#fff",
    bg: "#0ea5e9",
  },
  campus: {
    label: "Campus",
    description: "Campus and student signals",
    color: "#06110b",
    bg: "#34d399",
  },
  promoter: {
    label: "Promoter",
    description: "Promoter drops",
    color: "#fff",
    bg: "#fb3b64",
  },
  curated: {
    label: "Curated",
    description: "Findr-picked listings",
    color: "#160d03",
    bg: "#fbbf24",
  },
};

export const SOURCE_CONFIG: Record<
  Source,
  {
    label: string;
    color: string;
    bg: string;
    category: SourceCategory;
    cue: string;
    detailLabel: string;
  }
> = {
  partiful: {
    label: "Partiful",
    color: "#fff",
    bg: "#dc2743",
    category: "imported",
    cue: "Imported invite",
    detailLabel: "via Partiful",
  },
  eventbrite: {
    label: "Eventbrite",
    color: "#fff",
    bg: "#f0854a",
    category: "imported",
    cue: "Imported listing",
    detailLabel: "via Eventbrite",
  },
  plotz: {
    label: "Plotz",
    color: "#fff",
    bg: "#a855f7",
    category: "imported",
    cue: "Imported nightlife",
    detailLabel: "via Plotz",
  },
  user: {
    label: "User Submitted",
    color: "#fff",
    bg: "#0ea5e9",
    category: "community",
    cue: "Community post",
    detailLabel: "Community post",
  },
  dice: {
    label: "Dice",
    color: "#051016",
    bg: "#38bdf8",
    category: "imported",
    cue: "Imported ticketing",
    detailLabel: "via Dice",
  },
  campus: {
    label: "Campus",
    color: "#06110b",
    bg: "#34d399",
    category: "campus",
    cue: "Campus signal",
    detailLabel: "via Campus",
  },
  promoter: {
    label: "Promoter",
    color: "#fff",
    bg: "#fb3b64",
    category: "promoter",
    cue: "Promoter drop",
    detailLabel: "Promoter drop",
  },
  curated: {
    label: "Curated",
    color: "#160d03",
    bg: "#fbbf24",
    category: "curated",
    cue: "Findr pick",
    detailLabel: "Findr curated",
  },
};

// Intensity tiers for heat map legend
export const HEAT_TIERS = [
  { label: "EXPLOSIVE", color: "#dc2743", minFire: 150 },
  { label: "UNDERGROUND", color: "#a855f7", minFire: 60 },
  { label: "SOCIAL CHILL", color: "#34d399", minFire: 0 },
];

const VIBE_GRADIENTS: Record<Vibe, string[]> = {
  rave: [
    "radial-gradient(circle at 20% 18%, rgba(255,255,255,0.18), transparent 18%), linear-gradient(135deg, #150006 0%, #420818 42%, #96193c 72%, #dc2743 100%)",
    "radial-gradient(circle at 75% 18%, rgba(255,255,255,0.15), transparent 17%), linear-gradient(135deg, #05030b 0%, #24103a 42%, #771445 74%, #dc2743 100%)",
    "linear-gradient(135deg, #050008 0%, #26031f 35%, #731231 70%, #ff3b5f 100%)",
  ],
  darty: [
    "radial-gradient(circle at 18% 18%, rgba(255,255,255,0.2), transparent 16%), linear-gradient(135deg, #161000 0%, #4b2a08 42%, #b96523 72%, #f0854a 100%)",
    "linear-gradient(135deg, #140b00 0%, #3c2506 40%, #986323 72%, #fbbf24 100%)",
    "radial-gradient(circle at 72% 18%, rgba(255,255,255,0.18), transparent 16%), linear-gradient(135deg, #1a0900 0%, #4a1806 45%, #b94f23 76%, #f0854a 100%)",
  ],
  kickback: [
    "linear-gradient(135deg, #06150d 0%, #123224 42%, #1f6b4d 74%, #34d399 100%)",
    "radial-gradient(circle at 22% 20%, rgba(255,255,255,0.16), transparent 17%), linear-gradient(135deg, #07110b 0%, #172c25 44%, #2d6a4f 76%, #34d399 100%)",
    "linear-gradient(135deg, #05100d 0%, #122a2a 42%, #20675c 74%, #5eead4 100%)",
  ],
  house: [
    "linear-gradient(135deg, #160712 0%, #35142c 42%, #873a70 76%, #f472b6 100%)",
    "radial-gradient(circle at 72% 22%, rgba(255,255,255,0.16), transparent 17%), linear-gradient(135deg, #130913 0%, #2d1730 45%, #71315f 76%, #f472b6 100%)",
    "linear-gradient(135deg, #120611 0%, #311023 38%, #7c2f5e 72%, #fb7185 100%)",
  ],
  bar: [
    "linear-gradient(135deg, #06111f 0%, #112b4d 42%, #245f91 74%, #60a5fa 100%)",
    "radial-gradient(circle at 20% 20%, rgba(255,255,255,0.14), transparent 18%), linear-gradient(135deg, #071018 0%, #15283d 42%, #2e5c78 76%, #38bdf8 100%)",
    "linear-gradient(135deg, #080d18 0%, #18243a 40%, #334d7a 74%, #93c5fd 100%)",
  ],
  club: [
    "linear-gradient(135deg, #0b0614 0%, #261344 42%, #5a2290 74%, #a855f7 100%)",
    "radial-gradient(circle at 72% 18%, rgba(255,255,255,0.16), transparent 17%), linear-gradient(135deg, #090615 0%, #1d1542 42%, #512b8f 74%, #8b5cf6 100%)",
    "linear-gradient(135deg, #080713 0%, #241035 40%, #581c87 72%, #c084fc 100%)",
  ],
};

type EventSeed = Omit<FunctionEvent, "gradient"> & { gradient?: string };

function withGradients(events: EventSeed[]): FunctionEvent[] {
  const vibeCounts: Record<Vibe, number> = {
    rave: 0,
    darty: 0,
    kickback: 0,
    house: 0,
    bar: 0,
    club: 0,
  };

  return events.map((event) => {
    const gradients = VIBE_GRADIENTS[event.vibe];
    const gradient = event.gradient ?? gradients[vibeCounts[event.vibe] % gradients.length];
    vibeCounts[event.vibe] += 1;
    return { ...event, gradient };
  });
}

// Mock seed events only. Coordinates are intentionally approximate, general-area
// clusters around public nightlife zones so the demo map feels active without
// pointing to private addresses.
export const SEED_EVENTS: FunctionEvent[] = withGradients([
  {
    id: "seed-001",
    name: "SUBLEVEL 140",
    vibe: "rave",
    area: "SoFA District",
    time: "11:30 PM - 4:00 AM",
    source: "dice",
    fire: 284,
    lat: 37.3297,
    lng: -121.8868,
    description: "Basement-level techno, fog, and a late crowd moving after the bars close.",
    crowd: "220-280 expected",
    dress: "Black fits, sneakers fine",
    host: "Lowlight Collective",
  },
  {
    id: "seed-002",
    name: "NOIR FRIDAYS",
    vibe: "club",
    area: "Downtown Core",
    time: "10:00 PM - 2:00 AM",
    source: "promoter",
    fire: 241,
    lat: 37.3355,
    lng: -121.8898,
    description: "Bottle-service energy with a packed dance floor and early guest-list cutoff.",
    crowd: "180-240 expected",
    dress: "Elevated nightlife",
    host: "Motive Nights",
  },
  {
    id: "seed-003",
    name: "AFTERS IN THE CUT",
    vibe: "rave",
    area: "West End Industrial",
    time: "12:30 AM - 5:00 AM",
    source: "partiful",
    fire: 223,
    lat: 37.3342,
    lng: -121.9025,
    description: "After-hours sound system, warehouse visuals, and a location drop near midnight.",
    crowd: "160-210 expected",
    dress: "Utility layers",
    host: "Cut Signal",
  },
  {
    id: "seed-004",
    name: "BRKN BASS",
    vibe: "club",
    area: "South First",
    time: "10:30 PM - 2:30 AM",
    source: "dice",
    fire: 211,
    lat: 37.3312,
    lng: -121.8871,
    description: "High-tempo bass, guest DJs, and a line that usually moves before 11.",
    crowd: "160-220 expected",
    dress: "Statement jacket",
    host: "Room Service",
  },
  {
    id: "seed-005",
    name: "MIRROR ROOM",
    vibe: "club",
    area: "San Pedro Square",
    time: "9:30 PM - 1:30 AM",
    source: "eventbrite",
    fire: 196,
    lat: 37.3371,
    lng: -121.8942,
    description: "Polished top-40 and house edits for the crowd that wants easy momentum.",
    crowd: "140-190 expected",
    dress: "Clean going-out fits",
    host: "Glasshouse Presents",
  },
  {
    id: "seed-006",
    name: "ROOFTOP PRESET",
    vibe: "darty",
    area: "Downtown Core",
    time: "4:00 PM - 8:30 PM",
    source: "curated",
    fire: 182,
    lat: 37.336,
    lng: -121.8914,
    description: "Golden-hour drinks, house edits, and a crowd rolling straight into downtown.",
    crowd: "120-170 expected",
    dress: "Day-party clean",
    host: "Findr Picks",
  },
  {
    id: "seed-007",
    name: "11TH STREET HOUSE",
    vibe: "house",
    area: "Near Campus",
    time: "9:00 PM - 1:00 AM",
    source: "user",
    fire: 176,
    lat: 37.3367,
    lng: -121.8812,
    description: "Packed student house with backyard speakers and a fast-moving invite chain.",
    crowd: "90-140 expected",
    dress: "Campus casual",
    host: "Submitted by Maya",
  },
  {
    id: "seed-008",
    name: "STATIC HOUR",
    vibe: "rave",
    area: "SoFA District",
    time: "11:00 PM - 3:00 AM",
    source: "promoter",
    fire: 169,
    lat: 37.3304,
    lng: -121.8854,
    description: "Electro, breaks, and a darker room for people skipping the mainstream line.",
    crowd: "120-170 expected",
    dress: "Dark, breathable",
    host: "Signal Room",
  },
  {
    id: "seed-009",
    name: "HIGHLINE SATURDAY",
    vibe: "club",
    area: "Market Street",
    time: "10:00 PM - 2:00 AM",
    source: "eventbrite",
    fire: 154,
    lat: 37.3344,
    lng: -121.8904,
    description: "Main-room DJs, balcony hangs, and a crowd that peaks around midnight.",
    crowd: "130-180 expected",
    dress: "No athletic slides",
    host: "Highline Crew",
  },
  {
    id: "seed-010",
    name: "SUNSET YARD",
    vibe: "darty",
    area: "Japantown",
    time: "3:00 PM - 8:00 PM",
    source: "partiful",
    fire: 148,
    lat: 37.349,
    lng: -121.8956,
    description: "Backyard daylight set with picnic tables, coolers, and a friendly door.",
    crowd: "85-120 expected",
    dress: "Sunglasses required",
    host: "Northside Friends",
  },
  {
    id: "seed-011",
    name: "DAY ONES ONLY",
    vibe: "house",
    area: "Spartan Village",
    time: "8:30 PM - 12:30 AM",
    source: "campus",
    fire: 132,
    lat: 37.3376,
    lng: -121.8779,
    description: "Apartment function with a tight guest list, shared aux, and easy walkability.",
    crowd: "55-80 expected",
    dress: "Come as you are",
    host: "Campus Word",
  },
  {
    id: "seed-012",
    name: "MEZCAL TERRACE",
    vibe: "bar",
    area: "San Pedro Square",
    time: "7:00 PM - 11:30 PM",
    source: "curated",
    fire: 126,
    lat: 37.3368,
    lng: -121.8948,
    description: "Patio drinks, low-pressure mingling, and a reliable pregame before downtown.",
    crowd: "70-110 expected",
    dress: "Smart casual",
    host: "Findr Picks",
  },
  {
    id: "seed-013",
    name: "BASEMENT ROTATION",
    vibe: "house",
    area: "Campus South",
    time: "10:00 PM - 2:00 AM",
    source: "plotz",
    fire: 118,
    lat: 37.3313,
    lng: -121.8818,
    description: "Rotating DJs, cheap lights, and a crowd that keeps moving rooms.",
    crowd: "75-105 expected",
    dress: "Heat-proof fits",
    host: "Southside Rotation",
  },
  {
    id: "seed-014",
    name: "NIGHT FREQUENCY",
    vibe: "rave",
    area: "Little Italy",
    time: "11:45 PM - 4:30 AM",
    source: "promoter",
    fire: 112,
    lat: 37.3404,
    lng: -121.8987,
    description: "Raw room, minimal lighting, and deeper cuts for the late set.",
    crowd: "90-130 expected",
    dress: "All black encouraged",
    host: "Frequency Dept.",
  },
  {
    id: "seed-015",
    name: "PARKSIDE DAY PARTY",
    vibe: "darty",
    area: "Rose Garden Edge",
    time: "1:30 PM - 6:30 PM",
    source: "eventbrite",
    fire: 105,
    lat: 37.3314,
    lng: -121.9212,
    description: "Day drinks, lawn games, and an easygoing crowd before everyone splits up.",
    crowd: "80-130 expected",
    dress: "Light layers",
    host: "Parkside Social",
  },
  {
    id: "seed-016",
    name: "INDUSTRY NIGHT",
    vibe: "bar",
    area: "SoFA District",
    time: "8:00 PM - 12:00 AM",
    source: "promoter",
    fire: 98,
    lat: 37.3288,
    lng: -121.8859,
    description: "Bartenders, DJs, and friends-of-friends filling the room after dinner service.",
    crowd: "65-95 expected",
    dress: "Black tee approved",
    host: "Backbar Social",
  },
  {
    id: "seed-017",
    name: "VINYL & NATURAL WINE",
    vibe: "kickback",
    area: "The Alameda",
    time: "8:00 PM - 12:30 AM",
    source: "user",
    fire: 91,
    lat: 37.3421,
    lng: -121.9064,
    description: "Small apartment listening session with low lights, shared bottles, and no rush.",
    crowd: "25-40 expected",
    dress: "Soft layers",
    host: "Submitted by Ren",
  },
  {
    id: "seed-018",
    name: "AFTER DARK",
    vibe: "club",
    area: "The Alameda",
    time: "10:00 PM - 2:00 AM",
    source: "dice",
    fire: 88,
    lat: 37.3434,
    lng: -121.9069,
    description: "Moodier club night with R&B edits early and faster tracks after midnight.",
    crowd: "90-130 expected",
    dress: "Night-out casual",
    host: "Alameda Sound",
  },
  {
    id: "seed-019",
    name: "GOLDEN HOUR KITCHEN",
    vibe: "darty",
    area: "Midtown",
    time: "2:30 PM - 7:00 PM",
    source: "user",
    fire: 84,
    lat: 37.3267,
    lng: -121.9145,
    description: "Kitchen island pregame that spills into the patio before sunset.",
    crowd: "35-55 expected",
    dress: "Daytime casual",
    host: "Submitted by Jules",
  },
  {
    id: "seed-020",
    name: "JAZZ BAR PRE",
    vibe: "bar",
    area: "Downtown Core",
    time: "7:30 PM - 10:30 PM",
    source: "curated",
    fire: 78,
    lat: 37.3349,
    lng: -121.8919,
    description: "Seated drinks, live trio, and a calmer launch point for the rest of the night.",
    crowd: "45-75 expected",
    dress: "Date-night casual",
    host: "Findr Picks",
  },
  {
    id: "seed-021",
    name: "SPARTAN VILLAGE HOUSE",
    vibe: "house",
    area: "Spartan Village",
    time: "9:30 PM - 1:00 AM",
    source: "campus",
    fire: 74,
    lat: 37.3384,
    lng: -121.8787,
    description: "Dorm-adjacent house night with familiar faces and a soft cap at the door.",
    crowd: "45-70 expected",
    dress: "Campus casual",
    host: "Campus Word",
  },
  {
    id: "seed-022",
    name: "LAST CALL SOCIAL",
    vibe: "bar",
    area: "Downtown Core",
    time: "9:00 PM - 1:00 AM",
    source: "plotz",
    fire: 69,
    lat: 37.3358,
    lng: -121.8929,
    description: "Easy bar crawl anchor with groups checking in before picking the next move.",
    crowd: "50-85 expected",
    dress: "Anything but pajamas",
    host: "Plotz Radar",
  },
  {
    id: "seed-023",
    name: "BACK PATIO SESSION",
    vibe: "kickback",
    area: "Willow Glen",
    time: "7:00 PM - 11:00 PM",
    source: "partiful",
    fire: 63,
    lat: 37.3099,
    lng: -121.9022,
    description: "Grill, playlist, and a quieter crowd keeping the night warm but manageable.",
    crowd: "30-50 expected",
    dress: "Hoodie weather",
    host: "Patio People",
  },
  {
    id: "seed-024",
    name: "RSVP AT MIDNIGHT",
    vibe: "club",
    area: "SoFA District",
    time: "11:00 PM - 2:30 AM",
    source: "partiful",
    fire: 61,
    lat: 37.3294,
    lng: -121.8846,
    description: "Smaller dance room with a late guest list and a crowd that finds it by text.",
    crowd: "60-90 expected",
    dress: "Clean black",
    host: "Late List",
  },
  {
    id: "seed-025",
    name: "CAMPUS TAILGATE LATE",
    vibe: "darty",
    area: "Campus South",
    time: "5:00 PM - 10:00 PM",
    source: "campus",
    fire: 57,
    lat: 37.3319,
    lng: -121.8797,
    description: "Post-game hang with foldout tables, speakers, and groups passing through.",
    crowd: "55-90 expected",
    dress: "School colors",
    host: "Campus Word",
  },
  {
    id: "seed-026",
    name: "LOWKEY LIVING ROOM",
    vibe: "kickback",
    area: "Japantown",
    time: "8:30 PM - 12:00 AM",
    source: "user",
    fire: 52,
    lat: 37.3498,
    lng: -121.8969,
    description: "Couch-heavy kickback, card games, and a no-strangers mood.",
    crowd: "18-30 expected",
    dress: "Comfortable",
    host: "Submitted by Ari",
  },
  {
    id: "seed-027",
    name: "TAPROOM RUN",
    vibe: "bar",
    area: "Japantown",
    time: "6:30 PM - 10:30 PM",
    source: "curated",
    fire: 49,
    lat: 37.3482,
    lng: -121.894,
    description: "Group-friendly beers and a quiet first stop before the later plans form.",
    crowd: "35-60 expected",
    dress: "Casual",
    host: "Findr Picks",
  },
  {
    id: "seed-028",
    name: "HOUSE ROW LATE",
    vibe: "house",
    area: "Near Campus",
    time: "10:30 PM - 2:00 AM",
    source: "user",
    fire: 46,
    lat: 37.3359,
    lng: -121.8836,
    description: "Small house-row function with porch traffic and a playlist that changes hourly.",
    crowd: "35-60 expected",
    dress: "Campus casual",
    host: "Submitted by T",
  },
  {
    id: "seed-029",
    name: "LATE SYSTEM",
    vibe: "rave",
    area: "West End Industrial",
    time: "12:00 AM - 4:00 AM",
    source: "plotz",
    fire: 44,
    lat: 37.3333,
    lng: -121.9038,
    description: "Lower-key underground listing with a small room, heavy low end, and no frills.",
    crowd: "45-70 expected",
    dress: "Earplugs smart",
    host: "Plotz Radar",
  },
  {
    id: "seed-030",
    name: "FILM NIGHT AFTERS",
    vibe: "kickback",
    area: "The Alameda",
    time: "9:00 PM - 12:30 AM",
    source: "user",
    fire: 39,
    lat: 37.3413,
    lng: -121.9052,
    description: "Indie movie first, kitchen conversation after, and a smaller friend-of-friend list.",
    crowd: "20-32 expected",
    dress: "Soft casual",
    host: "Submitted by Cam",
  },
  {
    id: "seed-031",
    name: "PATIO PRE-GAME",
    vibe: "darty",
    area: "Santana Row",
    time: "4:30 PM - 8:00 PM",
    source: "eventbrite",
    fire: 34,
    lat: 37.3225,
    lng: -121.9472,
    description: "Happy-hour table groups and a polished pregame before people split downtown.",
    crowd: "40-65 expected",
    dress: "Clean daytime",
    host: "Weekend Social",
  },
  {
    id: "seed-032",
    name: "OPEN AUX HOUSE",
    vibe: "house",
    area: "Campus East",
    time: "8:00 PM - 12:00 AM",
    source: "campus",
    fire: 31,
    lat: 37.3372,
    lng: -121.8739,
    description: "Casual house hang where the queue is democratic and the crowd stays familiar.",
    crowd: "25-45 expected",
    dress: "No pressure",
    host: "Campus Word",
  },
  {
    id: "seed-033",
    name: "COUCH ROTATION",
    vibe: "kickback",
    area: "Spartan Village",
    time: "7:30 PM - 11:30 PM",
    source: "campus",
    fire: 28,
    lat: 37.3391,
    lng: -121.8795,
    description: "Board games, group chat invites, and a low-stakes room for people staying local.",
    crowd: "18-28 expected",
    dress: "Sweats welcome",
    host: "Campus Word",
  },
  {
    id: "seed-034",
    name: "LATE LOUNGE",
    vibe: "bar",
    area: "Santana Row",
    time: "8:30 PM - 12:30 AM",
    source: "curated",
    fire: 24,
    lat: 37.3218,
    lng: -121.9488,
    description: "Cocktail lounge energy for a smaller group that wants seats and conversation.",
    crowd: "25-45 expected",
    dress: "Polished casual",
    host: "Findr Picks",
  },
  {
    id: "seed-035",
    name: "LOFT LISTENING",
    vibe: "kickback",
    area: "Midtown",
    time: "8:00 PM - 11:30 PM",
    source: "partiful",
    fire: 18,
    lat: 37.3278,
    lng: -121.9131,
    description: "Small loft hang with vinyl, snacks, and a quieter guest list.",
    crowd: "16-24 expected",
    dress: "Relaxed",
    host: "Loft Friends",
  },
  {
    id: "seed-036",
    name: "ROOM 2",
    vibe: "rave",
    area: "Little Italy",
    time: "1:00 AM - 4:00 AM",
    source: "promoter",
    fire: 12,
    lat: 37.3394,
    lng: -121.8999,
    description: "Tiny late room for people who want one more set after the main night ends.",
    crowd: "25-40 expected",
    dress: "Dark and simple",
    host: "Room 2",
  },
]);
